package org.wahlzeit.model;

import static org.junit.Assert.*;

import org.junit.Assert;
import org.junit.Test;

/**
 * Provides tests for our SphericCoordinate. Getter and Setter testing is no longer needed because
 * of the ParameterUtil which is tested separately. equals and hashCode are generated by the ide so
 * there is also no need to test.
 */
public class SphericCoordinateTest {

  @Test
  public void distance() throws Exception {
    SphericCoordinate s1 = new SphericCoordinate(0, 0, 0);
    SphericCoordinate s2 = new SphericCoordinate(0, 0, 10);

    // distance from s1 to s2 should be the same
    Assert.assertEquals(s1.getDistance(s2), s2.getDistance(s1), 0.00001);

    // distance should be 10
    Assert.assertEquals(s1.getDistance(s2), 10.0, 0.00001);

    SphericCoordinate s3 = new SphericCoordinate(-90, 0, 10);
    SphericCoordinate s4 = new SphericCoordinate(90, 0, 10);

    // distance should be 20
    Assert.assertEquals(s3.getDistance(s4), 20.0, 0.00001);

    SphericCoordinate s5 = new SphericCoordinate(-90, 180, 10);
    SphericCoordinate s6 = new SphericCoordinate(90, 0, 10);

    // distance should be 20
    Assert.assertEquals(s5.getDistance(s6), 20.0, 0.00001);

  }

}